package UI;

import backend.ResultsBackend;
import backend.Statistics;
 import javax.swing.*;
import backend.TeamSheetsBoys;
import backend.TeamSheetsGirls;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SWG_T28
 */
public class AddResults extends javax.swing.JFrame {

    /**
     * Creates new form AddFixture
     */
    public AddResults() {
        initComponents();
        setLocationRelativeTo(null);
       
        DefaultComboBoxModel<String> comboModel1 = new DefaultComboBoxModel<String>();
        DefaultComboBoxModel<String> comboModel2 = new DefaultComboBoxModel<String>();
        DefaultComboBoxModel<String> comboModel3 = new DefaultComboBoxModel<String>();
        DefaultComboBoxModel<String> comboModel4 = new DefaultComboBoxModel<String>();
        DefaultComboBoxModel<String> comboModel5 = new DefaultComboBoxModel<String>();
        comboModel1.addElement("");
        comboModel2.addElement("");
        comboModel3.addElement("");
        comboModel4.addElement("");
        comboModel5.addElement("");
        String[] players = TeamSheetsGirls.getGirlsAsArray();
        for (int i = 0; i < players.length; i++) {
            comboModel1.addElement(players[i]);
            comboModel2.addElement(players[i]);
            comboModel3.addElement(players[i]);
            comboModel4.addElement(players[i]);
            comboModel5.addElement(players[i]);
        }
        Player1ComboBox.setModel(comboModel1);        // TODO add your handling code here:
        Player2ComboBox.setModel(comboModel2);        // TODO add your handling code here:
        Player3ComboBox.setModel(comboModel3);        // TODO add your handling code here:
        Player4ComboBox.setModel(comboModel4);        // TODO add your handling code here:
        Player5ComboBox.setModel(comboModel5);        // TODO add your handling code here:

       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        teamPicker = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CancelBUt = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Score = new javax.swing.JSpinner();
        ScoreRHB = new javax.swing.JSpinner();
        location = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        reddamTeamPicker = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Player1ComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Player2ComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Player3ComboBox = new javax.swing.JComboBox<>();
        Player4ComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Player5ComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1672, 619));

        jLabel1.setFont(new java.awt.Font("Gill Sans Nova", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Game Fixture");

        jLabel2.setFont(new java.awt.Font("Gill Sans Nova", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Teams");

        jLabel3.setFont(new java.awt.Font("Gill Sans Nova", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Score");

        jLabel4.setFont(new java.awt.Font("Gill Sans Nova", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Who scored");

        teamPicker.setBackground(new java.awt.Color(0, 0, 102));
        teamPicker.setForeground(new java.awt.Color(255, 255, 255));
        teamPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CrawfordNorthCoast", "CurroMountRichmore", "AstonCollage", "CrawfordLalucia", "RHU", " " }));
        teamPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamPickerActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Gill Sans Nova", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("vs");

        CancelBUt.setBackground(new java.awt.Color(255, 204, 0));
        CancelBUt.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        CancelBUt.setForeground(new java.awt.Color(0, 0, 0));
        CancelBUt.setText("Cancel");
        CancelBUt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelBUtMouseClicked(evt);
            }
        });
        CancelBUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBUtActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Reset");

        jButton3.setBackground(new java.awt.Color(255, 204, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Add and Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resume.png"))); // NOI18N

        Score.setFont(new java.awt.Font("Gill Sans Nova", 1, 12)); // NOI18N
        Score.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));

        ScoreRHB.setFont(new java.awt.Font("Gill Sans Nova", 1, 12)); // NOI18N
        ScoreRHB.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        ScoreRHB.setMaximumSize(new java.awt.Dimension(30, 0));
        ScoreRHB.setMinimumSize(new java.awt.Dimension(0, 0));
        ScoreRHB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScoreRHBMouseClicked(evt);
            }
        });

        location.setBackground(new java.awt.Color(0, 0, 102));
        location.setForeground(new java.awt.Color(255, 255, 255));
        location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home", "Away" }));
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Gill Sans Nova", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Location");

        reddamTeamPicker.setBackground(new java.awt.Color(0, 0, 102));
        reddamTeamPicker.setForeground(new java.awt.Color(255, 255, 255));
        reddamTeamPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RHBGirls", "RHBBoys" }));
        reddamTeamPicker.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                reddamTeamPickerItemStateChanged(evt);
            }
        });
        reddamTeamPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reddamTeamPickerActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Player 1");

        Player1ComboBox.setBackground(new java.awt.Color(0, 0, 102));
        Player1ComboBox.setForeground(new java.awt.Color(255, 255, 255));
        Player1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Player1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player1ComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Player 2");

        Player2ComboBox.setBackground(new java.awt.Color(0, 0, 102));
        Player2ComboBox.setForeground(new java.awt.Color(255, 255, 255));
        Player2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Player2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player2ComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Player 3");

        Player3ComboBox.setBackground(new java.awt.Color(0, 0, 102));
        Player3ComboBox.setForeground(new java.awt.Color(255, 255, 255));
        Player3ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Player3ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player3ComboBoxActionPerformed(evt);
            }
        });

        Player4ComboBox.setBackground(new java.awt.Color(0, 0, 102));
        Player4ComboBox.setForeground(new java.awt.Color(255, 255, 255));
        Player4ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Player4ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player4ComboBoxActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Player 4");

        Player5ComboBox.setBackground(new java.awt.Color(0, 0, 102));
        Player5ComboBox.setForeground(new java.awt.Color(255, 255, 255));
        Player5ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Player5ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player5ComboBoxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Player 5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(257, 257, 257)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(118, 118, 118)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(reddamTeamPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel6)
                                                        .addGap(82, 82, 82))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(ScoreRHB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(159, 159, 159)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(Score)
                                                        .addGap(129, 129, 129))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(teamPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Player1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Player2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Player3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Player4ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Player5ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addComponent(jLabel7)
                                .addGap(69, 69, 69))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CancelBUt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(67, 67, 67)))
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(reddamTeamPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teamPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScoreRHB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Player1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Player2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Player3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Player4ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Player5ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBUt)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teamPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamPickerActionPerformed
        // TODO add your handling code here:

     
    }//GEN-LAST:event_teamPickerActionPerformed

    private void CancelBUtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelBUtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelBUtMouseClicked

    private void CancelBUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBUtActionPerformed
        Results Info = new Results();
        Info.setVisible(true);        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_CancelBUtActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed

    }//GEN-LAST:event_locationActionPerformed

    private void reddamTeamPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reddamTeamPickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reddamTeamPickerActionPerformed

    private void Player1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player1ComboBoxActionPerformed

    }//GEN-LAST:event_Player1ComboBoxActionPerformed

    private void Player2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player2ComboBoxActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_Player2ComboBoxActionPerformed

    private void Player3ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player3ComboBoxActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_Player3ComboBoxActionPerformed

    private void Player4ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player4ComboBoxActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_Player4ComboBoxActionPerformed

    private void Player5ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player5ComboBoxActionPerformed
          // TODO add your handling code here:
    }//GEN-LAST:event_Player5ComboBoxActionPerformed

    private void reddamTeamPickerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_reddamTeamPickerItemStateChanged

        String team = (String) reddamTeamPicker.getActionCommand();
        
        DefaultComboBoxModel<String> comboModel1 = new DefaultComboBoxModel<String>();
        DefaultComboBoxModel<String> comboModel2 = new DefaultComboBoxModel<String>();
        DefaultComboBoxModel<String> comboModel3 = new DefaultComboBoxModel<String>();
        DefaultComboBoxModel<String> comboModel4 = new DefaultComboBoxModel<String>();
        DefaultComboBoxModel<String> comboModel5 = new DefaultComboBoxModel<String>();
        comboModel1.addElement("");
        comboModel2.addElement("");
        comboModel3.addElement("");
        comboModel4.addElement("");
        comboModel5.addElement("");
        String[] players = TeamSheetsBoys.getBoysAsArray();
        for (int i = 0; i < players.length; i++) {
            comboModel1.addElement(players[i]);
            comboModel2.addElement(players[i]);
            comboModel3.addElement(players[i]);
            comboModel4.addElement(players[i]);
            comboModel5.addElement(players[i]);
        }
        Player1ComboBox.setModel(comboModel1);        // TODO add your handling code here:
        Player2ComboBox.setModel(comboModel2);        // TODO add your handling code here:
        Player3ComboBox.setModel(comboModel3);        // TODO add your handling code here:
        Player4ComboBox.setModel(comboModel4);        // TODO add your handling code here:
        Player5ComboBox.setModel(comboModel5);        // TODO add your handling code here:

                                         // TODO add your handling code here:
                                         
       
    }//GEN-LAST:event_reddamTeamPickerItemStateChanged

    private void ScoreRHBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScoreRHBMouseClicked
        SpinnerModel sm = new SpinnerNumberModel(0, 0, 9, 1); 
        JSpinner spinner = new JSpinner(sm);
        
    }//GEN-LAST:event_ScoreRHBMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String rhbTeam = (String)reddamTeamPicker.getSelectedItem();        // TODO add your handling code here:
    String otherTeam = (String)teamPicker.getSelectedItem();        // TODO add your handling code here:
    String Location = (String)location.getSelectedItem();        // TODO add your handling code here:
    String player1 = (String)Player1ComboBox.getSelectedItem();    
     Statistics.editBoysStats(player1, player1);
// TODO add your handling code here:
    String player2 = (String)Player2ComboBox.getSelectedItem(); 
    Statistics.editBoysStats(player2, player2);// TODO add your handling code here:
    String player3 = (String)Player3ComboBox.getSelectedItem(); 
    Statistics.editBoysStats(player3, player3);// TODO add your handling code here:
    String player4 = (String)Player4ComboBox.getSelectedItem(); 
    Statistics.editBoysStats(player4, player4);// TODO add your handling code here:
    String player5 = (String)Player5ComboBox.getSelectedItem();  
    Statistics.editBoysStats(player5, player5);// TODO add your handling code here:
    int reddamScore = (int) ScoreRHB.getValue();        // TODO add your handling code here:
    int opponentScore = (int)Score.getValue();   
    
    ResultsBackend.addResult("vs",player1, player2, player3, player4, player5, rhbTeam, otherTeam, reddamScore, opponentScore, Location);
// TODO add your handling code here:
     
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBUt;
    private javax.swing.JComboBox<String> Player1ComboBox;
    private javax.swing.JComboBox<String> Player2ComboBox;
    private javax.swing.JComboBox<String> Player3ComboBox;
    private javax.swing.JComboBox<String> Player4ComboBox;
    private javax.swing.JComboBox<String> Player5ComboBox;
    private javax.swing.JSpinner Score;
    private javax.swing.JSpinner ScoreRHB;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> location;
    private javax.swing.JComboBox<String> reddamTeamPicker;
    private javax.swing.JComboBox<String> teamPicker;
    // End of variables declaration//GEN-END:variables
}
